version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - IBKR_GATEWAY_URL=localhost
      - IBIND_PORT=5001
    restart: unless-stopped
    depends_on:
      - ibkr_gateway
    network_mode: host

  ibkr_gateway:
    build:
      context: .
      dockerfile: Dockerfile.ibkr_gateway
      args:
        - IBKR_GATEWAY_PORT=5001
    ports:
      - "5001:5001"
    restart: unless-stopped
    network_mode: host
