version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - ibkr_gateway
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ibkr_gateway:
    build:
      context: .
      dockerfile: Dockerfile.ibkr_gateway
      args:
        - IBKR_GATEWAY_PORT=${IBKR_GATEWAY_PORT}
    ports:
      - "5001:5001"
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
